apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web_nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
